-- 085_add_col_account_upload_receipt.sql
-- Add account_bill.upload_receipt_id 
-- May 6, 2026
-- Jack Wong ; 

DELIMITER $$

DROP PROCEDURE IF EXISTS add_col_account_upload_receipt $$
CREATE PROCEDURE add_col_account_upload_receipt()
BEGIN
    DECLARE col_exists      INT DEFAULT 0;
    DECLARE index_exists    INT DEFAULT 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'status_id';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN status_id INT UNSIGNED    
        AFTER flag;
    END IF;
    
    
    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'payment_channel_id';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN payment_channel_id INT UNSIGNED    
        AFTER status_id;
    END IF;
    
    
    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'amount_receipt';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN amount_receipt DECIMAL(8,2) UNSIGNED 
        COMMENT 'Amount paid as shown on the receipt upload by user'   
        AFTER payment_channel_id;
    END IF;
    
    
    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'payment_reference';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN payment_reference VARCHAR(32)
        COMMENT 'Reference string shown on the receipt; This is generated by bank or payment system'
        AFTER amount_receipt;
    END IF;
    

    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'dt_receipt';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN dt_receipt DATETIME 
        COMMENT 'Datetime printed on receipt'   
        AFTER payment_reference;
    END IF;
    
    
    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'data_entry_user_id';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN data_entry_user_id INT UNSIGNED  
        COMMENT 'User who manually entered receipt details'  
        AFTER dt_receipt;
    END IF;
    
    
    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'dt_input_data_entry';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN dt_input_data_entry DATETIME    
        COMMENT 'Datetime when the receipt details was inputted'
        AFTER data_entry_user_id;
    END IF;
    
    


    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'amount_verified';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN amount_verified DECIMAL(8,2) UNSIGNED
        COMMENT 'Verified amount in the payment channel after referencing payment_reference'    
        AFTER dt_receipt;
    END IF;
    
    
    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'payment_verified_user_id';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN payment_verified_user_id INT UNSIGNED
        COMMENT 'User who manually verified the payment'    
        AFTER amount_verified;
    END IF;
    
    
    SET col_exists = 0;
    
    SELECT COUNT(*) INTO col_exists
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND COLUMN_NAME = 'dt_payment_verified';
    
    IF col_exists = 0 THEN
        ALTER TABLE account_upload_receipt
        ADD COLUMN dt_payment_verified DATETIME
        COMMENT 'When the payment was verified'    
        AFTER payment_verified_user_id;
    END IF;
    
    
    SELECT COUNT(*) INTO index_exists
    FROM INFORMATION_SCHEMA.STATISTICS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND INDEX_NAME = 'INDEX_ACCOUNT_BILL_ID';

    IF index_exists = 0 THEN
        CREATE INDEX INDEX_ACCOUNT_BILL_ID 
        ON account_upload_receipt (account_bill_id);
    END IF;
    
    
    SET index_exists = 0;
    
    SELECT COUNT(*) INTO index_exists
    FROM INFORMATION_SCHEMA.STATISTICS 
    WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'account_upload_receipt' 
        AND INDEX_NAME = 'INDEX_PAYMENT_CHANNEL_ID';

    IF index_exists = 0 THEN
        CREATE INDEX INDEX_PAYMENT_CHANNEL_ID 
        ON account_upload_receipt (payment_channel_id);
    END IF;
    
    
END$$

DELIMITER ;

CALL add_col_account_upload_receipt();
DROP PROCEDURE add_col_account_upload_receipt;
